"milestones":
  - "title": "0.1.0"
    "description": "Minor release – targeting 0.1.x branch (semantic version: 0.1.0)"
    "state": "open"
  - "title": "1.0.0"
    "description": "Major release – targeting 1.0.x branch (semantic version: 1.0.0)"
    "state": "open"
"repository":
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "allow_squash_merge": true
  "default_branch": "0.1.x"
  "delete_branch_on_merge": true
  "description": "[WIP] Nix tool for PHP"
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
  "has_downloads": true
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "homepage": "https://github.com/nix-php/nixify"
  "name": "nixify"
  "topics": "ghostwriter, nix, nix-php, nixify"
  "allow_auto_merge": true
  "allow_forking": true
  "allow_update_branch": true
  "security_and_analysis":
    "advanced_security":
      "status": "enabled"
    "code_security":
      "status": "enabled"
    "secret_scanning":
      "status": "enabled"
    "secret_scanning_ai_detection":
      "status": "enabled"
    "secret_scanning_non_provider_patterns":
      "status": "enabled"
    "secret_scanning_push_protection":
      "status": "enabled"
  "web_commit_signoff_required": true
